"""Add last_workspace_preset_id to UserOrganizationMembership

Revision ID: 04f909921585
Revises: 263414709dda
Create Date: 2026-03-11 22:38:31.654527

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "04f909921585"
down_revision = "263414709dda"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_organization_memberships", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "last_workspace_preset_id",
                sa.Integer(),
                nullable=True,
                comment="Last workspace preset loaded by this user in this org",
            )
        )
        batch_op.create_foreign_key(
            None, "user_filter_presets", ["last_workspace_preset_id"], ["id"], ondelete="SET NULL"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_organization_memberships", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("last_workspace_preset_id")

    # ### end Alembic commands ###
