"""add assistant_enabled to user

Revision ID: 0f4c84e5c919
Revises: 473a26b8dbe8
Create Date: 2026-03-31 09:41:27.769598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f4c84e5c919'
down_revision = '473a26b8dbe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assistant_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('assistant_enabled')

    # ### end Alembic commands ###
