"""Add per-organization user permissions

Revision ID: 119d8257cb6a
Revises: 0e11e44f5949
Create Date: 2026-03-08 18:27:36.930839

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "119d8257cb6a"
down_revision = "0e11e44f5949"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with server default for existing rows
    with op.batch_alter_table("user_organization_memberships", schema=None) as batch_op:
        batch_op.add_column(sa.Column("can_manage_value_types", sa.Boolean(), nullable=False, server_default="true"))
        batch_op.add_column(sa.Column("can_manage_challenges", sa.Boolean(), nullable=False, server_default="true"))
        batch_op.add_column(sa.Column("can_manage_initiatives", sa.Boolean(), nullable=False, server_default="true"))
        batch_op.add_column(sa.Column("can_manage_systems", sa.Boolean(), nullable=False, server_default="true"))
        batch_op.add_column(sa.Column("can_manage_kpis", sa.Boolean(), nullable=False, server_default="true"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_organization_memberships", schema=None) as batch_op:
        batch_op.drop_column("can_manage_kpis")
        batch_op.drop_column("can_manage_systems")
        batch_op.drop_column("can_manage_initiatives")
        batch_op.drop_column("can_manage_challenges")
        batch_op.drop_column("can_manage_value_types")

    # ### end Alembic commands ###
