"""Remove is_default from UserFilterPreset (only use last-used tracking)

Revision ID: 16138fd82405
Revises: 04f909921585
Create Date: 2026-03-11 22:46:26.334297

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "16138fd82405"
down_revision = "04f909921585"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_filter_presets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_user_org_default"))
        batch_op.drop_column("is_default")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_filter_presets", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_default",
                sa.BOOLEAN(),
                autoincrement=False,
                nullable=False,
                comment="Auto-load this preset when entering workspace",
            )
        )
        batch_op.create_index(
            batch_op.f("idx_user_org_default"), ["user_id", "organization_id", "is_default"], unique=False
        )

    # ### end Alembic commands ###
