"""Add TestExecution model for test history tracking

Revision ID: 19d31425d0e7
Revises: p6k7l8m9n0o1
Create Date: 2026-03-19 10:19:22.859011

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "19d31425d0e7"
down_revision = "p6k7l8m9n0o1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test_executions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("executed_at", sa.DateTime(), nullable=False),
        sa.Column("executed_by_user_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("total_tests", sa.Integer(), nullable=True),
        sa.Column("passed_tests", sa.Integer(), nullable=True),
        sa.Column("failed_tests", sa.Integer(), nullable=True),
        sa.Column("skipped_tests", sa.Integer(), nullable=True),
        sa.Column("error_tests", sa.Integer(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("coverage_percent", sa.Float(), nullable=True),
        sa.Column("covered_lines", sa.Integer(), nullable=True),
        sa.Column("total_lines", sa.Integer(), nullable=True),
        sa.Column("missing_lines", sa.Integer(), nullable=True),
        sa.Column("failed_test_details", sa.JSON(), nullable=True),
        sa.Column("coverage_by_module", sa.JSON(), nullable=True),
        sa.Column("python_version", sa.String(length=50), nullable=True),
        sa.Column("environment", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(["executed_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("test_executions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_test_executions_executed_at"), ["executed_at"], unique=False)

    with op.batch_alter_table("action_item_mentions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_action_item_mentions_action_item_id"))

    with op.batch_alter_table("action_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_action_items_organization_id"))
        batch_op.drop_index(batch_op.f("ix_action_items_owner_user_id"))
        batch_op.drop_index(batch_op.f("ix_action_items_status"))
        batch_op.drop_index(batch_op.f("ix_action_items_visibility"))

    with op.batch_alter_table("saved_search", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_saved_search_user_org"))

    with op.batch_alter_table("stakeholders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_stakeholders_organization_id"))

    with op.batch_alter_table("user_organization_memberships", schema=None) as batch_op:
        batch_op.alter_column(
            "can_view_action_items",
            existing_type=sa.BOOLEAN(),
            comment="View action register",
            existing_nullable=False,
            existing_server_default=sa.text("true"),
        )
        batch_op.alter_column(
            "can_create_action_items",
            existing_type=sa.BOOLEAN(),
            comment="Create/edit action items",
            existing_nullable=False,
            existing_server_default=sa.text("true"),
        )
        batch_op.alter_column(
            "can_view_stakeholders",
            existing_type=sa.BOOLEAN(),
            comment="View stakeholders",
            existing_nullable=False,
            existing_server_default=sa.text("false"),
        )
        batch_op.alter_column(
            "can_manage_stakeholders",
            existing_type=sa.BOOLEAN(),
            comment="Create/edit stakeholders",
            existing_nullable=False,
            existing_server_default=sa.text("false"),
        )
        batch_op.alter_column(
            "can_view_map",
            existing_type=sa.BOOLEAN(),
            comment="View map dashboard",
            existing_nullable=False,
            existing_server_default=sa.text("true"),
        )
        batch_op.alter_column(
            "can_edit_porters",
            existing_type=sa.BOOLEAN(),
            comment="Edit Porter's Five Forces analysis",
            existing_nullable=False,
            existing_server_default=sa.text("true"),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_organization_memberships", schema=None) as batch_op:
        batch_op.alter_column(
            "can_edit_porters",
            existing_type=sa.BOOLEAN(),
            comment=None,
            existing_comment="Edit Porter's Five Forces analysis",
            existing_nullable=False,
            existing_server_default=sa.text("true"),
        )
        batch_op.alter_column(
            "can_view_map",
            existing_type=sa.BOOLEAN(),
            comment=None,
            existing_comment="View map dashboard",
            existing_nullable=False,
            existing_server_default=sa.text("true"),
        )
        batch_op.alter_column(
            "can_manage_stakeholders",
            existing_type=sa.BOOLEAN(),
            comment=None,
            existing_comment="Create/edit stakeholders",
            existing_nullable=False,
            existing_server_default=sa.text("false"),
        )
        batch_op.alter_column(
            "can_view_stakeholders",
            existing_type=sa.BOOLEAN(),
            comment=None,
            existing_comment="View stakeholders",
            existing_nullable=False,
            existing_server_default=sa.text("false"),
        )
        batch_op.alter_column(
            "can_create_action_items",
            existing_type=sa.BOOLEAN(),
            comment=None,
            existing_comment="Create/edit action items",
            existing_nullable=False,
            existing_server_default=sa.text("true"),
        )
        batch_op.alter_column(
            "can_view_action_items",
            existing_type=sa.BOOLEAN(),
            comment=None,
            existing_comment="View action register",
            existing_nullable=False,
            existing_server_default=sa.text("true"),
        )

    with op.batch_alter_table("stakeholders", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_stakeholders_organization_id"), ["organization_id"], unique=False)

    with op.batch_alter_table("saved_search", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_saved_search_user_org"), ["user_id", "organization_id"], unique=False)

    with op.batch_alter_table("action_items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_action_items_visibility"), ["visibility"], unique=False)
        batch_op.create_index(batch_op.f("ix_action_items_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_action_items_owner_user_id"), ["owner_user_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_action_items_organization_id"), ["organization_id"], unique=False)

    with op.batch_alter_table("action_item_mentions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_action_item_mentions_action_item_id"), ["action_item_id"], unique=False)

    with op.batch_alter_table("test_executions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_test_executions_executed_at"))

    op.drop_table("test_executions")
    # ### end Alembic commands ###
