"""add impact_levels table and impact_level to entities

Revision ID: 1f7bd9f9e317
Revises: a79e05c402c8
Create Date: 2026-03-28 12:48:03.368011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f7bd9f9e317'
down_revision = 'a79e05c402c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impact_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False, comment='1, 2, or 3'),
    sa.Column('label', sa.String(length=50), nullable=False, comment='e.g., Low, Medium, High'),
    sa.Column('icon', sa.String(length=50), nullable=True, comment='Bootstrap icon class or emoji'),
    sa.Column('weight', sa.Integer(), nullable=False, comment='Integer weight for rollup'),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'level', name='uq_impact_level_org_level')
    )
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('impact_level', sa.Integer(), nullable=True, comment='1/2/3 = org impact levels, NULL = not assessed'))

    with op.batch_alter_table('initiatives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('impact_level', sa.Integer(), nullable=True, comment='1/2/3 = org impact levels, NULL = not assessed'))
        batch_op.alter_column('impact_on_challenge',
               existing_type=sa.VARCHAR(length=20),
               comment='Legacy: not_assessed, low, medium, high, no_consensus',
               existing_comment='Impact level on challenge: not_assessed, low, medium, high, no_consensus',
               existing_nullable=True)

    with op.batch_alter_table('kpis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('impact_level', sa.Integer(), nullable=True, comment='1/2/3 = org impact levels, NULL = not assessed'))

    with op.batch_alter_table('spaces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('impact_level', sa.Integer(), nullable=True, comment='1/2/3 = org impact levels, NULL = not assessed'))

    with op.batch_alter_table('systems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('impact_level', sa.Integer(), nullable=True, comment='1/2/3 = org impact levels, NULL = not assessed'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('systems', schema=None) as batch_op:
        batch_op.drop_column('impact_level')

    with op.batch_alter_table('spaces', schema=None) as batch_op:
        batch_op.drop_column('impact_level')

    with op.batch_alter_table('kpis', schema=None) as batch_op:
        batch_op.drop_column('impact_level')

    with op.batch_alter_table('initiatives', schema=None) as batch_op:
        batch_op.alter_column('impact_on_challenge',
               existing_type=sa.VARCHAR(length=20),
               comment='Impact level on challenge: not_assessed, low, medium, high, no_consensus',
               existing_comment='Legacy: not_assessed, low, medium, high, no_consensus',
               existing_nullable=True)
        batch_op.drop_column('impact_level')

    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.drop_column('impact_level')

    op.drop_table('impact_levels')
    # ### end Alembic commands ###
