"""Add UserFilterPreset model for saving workspace filters

Revision ID: 263414709dda
Revises: e25c8ab9a347
Create Date: 2026-03-11 22:05:06.188612

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "263414709dda"
down_revision = "e25c8ab9a347"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_filter_presets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False, comment="User-defined name for this filter preset"),
        sa.Column("is_default", sa.Boolean(), nullable=False, comment="Auto-load this preset when entering workspace"),
        sa.Column(
            "filters",
            sa.JSON(),
            nullable=False,
            comment="Complete filter state including: space_type, governance_bodies, groups, show_archived, show_all_columns, show_levels",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "organization_id", "name", name="uq_user_org_preset_name"),
    )
    with op.batch_alter_table("user_filter_presets", schema=None) as batch_op:
        batch_op.create_index("idx_user_org_default", ["user_id", "organization_id", "is_default"], unique=False)
        batch_op.create_index(batch_op.f("ix_user_filter_presets_organization_id"), ["organization_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_user_filter_presets_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_filter_presets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_filter_presets_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_filter_presets_organization_id"))
        batch_op.drop_index("idx_user_org_default")

    op.drop_table("user_filter_presets")
    # ### end Alembic commands ###
