"""add description to value_types

Revision ID: 41612386c9e6
Revises: b4c5d6e7f8g9
Create Date: 2026-03-28 08:05:54.004545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41612386c9e6'
down_revision = 'b4c5d6e7f8g9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_organization_memberships', schema=None) as batch_op:
        batch_op.alter_column('can_view_snapshots',
               existing_type=sa.BOOLEAN(),
               comment='View snapshots',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('can_create_snapshots',
               existing_type=sa.BOOLEAN(),
               comment='Create snapshots',
               existing_nullable=False,
               existing_server_default=sa.text('true'))

    with op.batch_alter_table('value_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True, comment='Short description of what this value type measures'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('value_types', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('user_organization_memberships', schema=None) as batch_op:
        batch_op.alter_column('can_create_snapshots',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Create snapshots',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('can_view_snapshots',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='View snapshots',
               existing_nullable=False,
               existing_server_default=sa.text('true'))

    # ### end Alembic commands ###
