"""add decisions to initiative_progress_updates

Revision ID: 46e8f568eb5e
Revises: bca33dac9ddd
Create Date: 2026-03-28 22:43:24.205946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46e8f568eb5e'
down_revision = 'bca33dac9ddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('initiative_progress_updates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decisions', sa.Text(), nullable=True, comment='Decisions taken during this update'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('initiative_progress_updates', schema=None) as batch_op:
        batch_op.drop_column('decisions')

    # ### end Alembic commands ###
