"""add rollup_cache table

Revision ID: 473a26b8dbe8
Revises: 9a167e899970
Create Date: 2026-03-31 07:26:36.266665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '473a26b8dbe8'
down_revision = '9a167e899970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rollup_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('value_type_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('formatted_value', sa.String(length=100), nullable=True),
    sa.Column('unit_label', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('formula', sa.String(length=20), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('count_total', sa.Integer(), nullable=True),
    sa.Column('count_included', sa.Integer(), nullable=True),
    sa.Column('list_label', sa.String(length=200), nullable=True),
    sa.Column('list_color', sa.String(length=20), nullable=True),
    sa.Column('consensus_status', sa.String(length=20), nullable=True),
    sa.Column('consensus_count', sa.Integer(), nullable=True),
    sa.Column('calculation_type', sa.String(length=20), nullable=True),
    sa.Column('has_target', sa.Boolean(), nullable=True),
    sa.Column('target_value_formatted', sa.String(length=100), nullable=True),
    sa.Column('target_date', sa.String(length=20), nullable=True),
    sa.Column('target_direction', sa.String(length=20), nullable=True),
    sa.Column('target_progress', sa.Integer(), nullable=True),
    sa.Column('target_color', sa.String(length=20), nullable=True),
    sa.Column('comments_tooltip', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['value_type_id'], ['value_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'entity_type', 'entity_id', 'value_type_id', name='uq_rollup_cache_entity_vt')
    )
    with op.batch_alter_table('rollup_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rollup_cache_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rollup_cache_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index('ix_rollup_cache_org_entity', ['organization_id', 'entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rollup_cache_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rollup_cache_value_type_id'), ['value_type_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rollup_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rollup_cache_value_type_id'))
        batch_op.drop_index(batch_op.f('ix_rollup_cache_organization_id'))
        batch_op.drop_index('ix_rollup_cache_org_entity')
        batch_op.drop_index(batch_op.f('ix_rollup_cache_entity_type'))
        batch_op.drop_index(batch_op.f('ix_rollup_cache_entity_id'))

    op.drop_table('rollup_cache')
    # ### end Alembic commands ###
