"""Add time-series snapshots and collaboration features (comments, mentions)

Revision ID: 498afb934c2e
Revises: 
Create Date: 2026-03-07 13:18:13.594665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '498afb934c2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rollup_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('snapshot_label', sa.String(length=100), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('value_type_id', sa.Integer(), nullable=False),
    sa.Column('rollup_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('qualitative_level', sa.Integer(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('child_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['value_type_id'], ['value_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rollup_snapshots', schema=None) as batch_op:
        batch_op.create_index('idx_rollup_date', ['snapshot_date'], unique=False)
        batch_op.create_index('idx_rollup_entity_date', ['entity_type', 'entity_id', 'value_type_id', 'snapshot_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_rollup_snapshots_snapshot_date'), ['snapshot_date'], unique=False)

    op.create_table('cell_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kpi_value_type_config_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('mentioned_user_ids', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['kpi_value_type_config_id'], ['kpi_value_type_configs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['cell_comments.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cell_comments', schema=None) as batch_op:
        batch_op.create_index('idx_comment_config', ['kpi_value_type_config_id'], unique=False)
        batch_op.create_index('idx_comment_parent', ['parent_comment_id'], unique=False)
        batch_op.create_index('idx_comment_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cell_comments_kpi_value_type_config_id'), ['kpi_value_type_config_id'], unique=False)

    op.create_table('kpi_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kpi_value_type_config_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('snapshot_label', sa.String(length=100), nullable=True),
    sa.Column('consensus_status', sa.String(length=50), nullable=False),
    sa.Column('consensus_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('qualitative_level', sa.Integer(), nullable=True),
    sa.Column('contributor_count', sa.Integer(), nullable=True),
    sa.Column('is_rollup_eligible', sa.Boolean(), nullable=True),
    sa.Column('contributing_values', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['kpi_value_type_config_id'], ['kpi_value_type_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kpi_snapshots', schema=None) as batch_op:
        batch_op.create_index('idx_snapshot_config_date', ['kpi_value_type_config_id', 'snapshot_date'], unique=False)
        batch_op.create_index('idx_snapshot_date', ['snapshot_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_kpi_snapshots_kpi_value_type_config_id'), ['kpi_value_type_config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kpi_snapshots_snapshot_date'), ['snapshot_date'], unique=False)

    op.create_table('mention_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentioned_user_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['cell_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mentioned_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mention_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mention_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_mention_notifications_mentioned_user_id'), ['mentioned_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mention_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mention_notifications_mentioned_user_id'))
        batch_op.drop_index(batch_op.f('ix_mention_notifications_is_read'))

    op.drop_table('mention_notifications')
    with op.batch_alter_table('kpi_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kpi_snapshots_snapshot_date'))
        batch_op.drop_index(batch_op.f('ix_kpi_snapshots_kpi_value_type_config_id'))
        batch_op.drop_index('idx_snapshot_date')
        batch_op.drop_index('idx_snapshot_config_date')

    op.drop_table('kpi_snapshots')
    with op.batch_alter_table('cell_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cell_comments_kpi_value_type_config_id'))
        batch_op.drop_index('idx_comment_user')
        batch_op.drop_index('idx_comment_parent')
        batch_op.drop_index('idx_comment_config')

    op.drop_table('cell_comments')
    with op.batch_alter_table('rollup_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rollup_snapshots_snapshot_date'))
        batch_op.drop_index('idx_rollup_entity_date')
        batch_op.drop_index('idx_rollup_date')

    op.drop_table('rollup_snapshots')
    # ### end Alembic commands ###
