"""Add mobile_beta_tester column to users

Revision ID: 551babdaeb39
Revises: fcbf234294da
Create Date: 2026-03-15 22:35:29.955871

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "551babdaeb39"
down_revision = "fcbf234294da"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("entity_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_entity_links_created_by"))
        batch_op.drop_index(batch_op.f("ix_entity_links_entity_type_id"))

    with op.batch_alter_table("entity_type_defaults", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_entity_type_defaults_entity_type"), ["entity_type"], unique=False)

    with op.batch_alter_table("geography_countries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_geography_countries_region_id"))

    with op.batch_alter_table("geography_regions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_geography_regions_organization_id"))

    with op.batch_alter_table("geography_sites", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_geography_sites_country_id"))
        batch_op.drop_index(batch_op.f("ix_geography_sites_is_active"))

    with op.batch_alter_table("kpi_geography_assignments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_kpi_geography_assignments_country_id"))
        batch_op.drop_index(batch_op.f("ix_kpi_geography_assignments_kpi_id"))
        batch_op.drop_index(batch_op.f("ix_kpi_geography_assignments_region_id"))
        batch_op.drop_index(batch_op.f("ix_kpi_geography_assignments_site_id"))

    with op.batch_alter_table("kpi_site_assignments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_kpi_site_assignments_kpi_id"))
        batch_op.drop_index(batch_op.f("ix_kpi_site_assignments_site_id"))

    with op.batch_alter_table("kpi_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_kpi_snapshot_period"))
        batch_op.create_index(batch_op.f("ix_kpi_snapshots_year"), ["year"], unique=False)

    with op.batch_alter_table("rollup_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_rollup_snapshot_period"))
        batch_op.create_index(batch_op.f("ix_rollup_snapshots_year"), ["year"], unique=False)

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mobile_beta_tester", sa.Boolean(), nullable=False, server_default="false"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("mobile_beta_tester")

    with op.batch_alter_table("rollup_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rollup_snapshots_year"))
        batch_op.create_index(batch_op.f("idx_rollup_snapshot_period"), ["year", "quarter", "month"], unique=False)

    with op.batch_alter_table("kpi_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_kpi_snapshots_year"))
        batch_op.create_index(batch_op.f("idx_kpi_snapshot_period"), ["year", "quarter", "month"], unique=False)

    with op.batch_alter_table("kpi_site_assignments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_kpi_site_assignments_site_id"), ["site_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_kpi_site_assignments_kpi_id"), ["kpi_id"], unique=False)

    with op.batch_alter_table("kpi_geography_assignments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_kpi_geography_assignments_site_id"), ["site_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_kpi_geography_assignments_region_id"), ["region_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_kpi_geography_assignments_kpi_id"), ["kpi_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_kpi_geography_assignments_country_id"), ["country_id"], unique=False)

    with op.batch_alter_table("geography_sites", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_geography_sites_is_active"), ["is_active"], unique=False)
        batch_op.create_index(batch_op.f("ix_geography_sites_country_id"), ["country_id"], unique=False)

    with op.batch_alter_table("geography_regions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_geography_regions_organization_id"), ["organization_id"], unique=False)

    with op.batch_alter_table("geography_countries", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_geography_countries_region_id"), ["region_id"], unique=False)

    with op.batch_alter_table("entity_type_defaults", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_entity_type_defaults_entity_type"))

    with op.batch_alter_table("entity_links", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_entity_links_entity_type_id"), ["entity_type", "entity_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_entity_links_created_by"), ["created_by"], unique=False)

    # ### end Alembic commands ###
