"""Add governance bodies and KPI governance body links

Revision ID: 597259f31427
Revises: c9d4e8f2a1b3
Create Date: 2026-03-08 21:05:28.459400

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "597259f31427"
down_revision = "c9d4e8f2a1b3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "governance_bodies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("abbreviation", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("color", sa.String(length=7), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "kpi_governance_body_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kpi_id", sa.Integer(), nullable=False),
        sa.Column("governance_body_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["governance_body_id"], ["governance_bodies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["kpi_id"], ["kpis.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kpi_id", "governance_body_id", name="uq_kpi_governance_body"),
    )
    with op.batch_alter_table("user_organization_memberships", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("can_manage_governance_bodies", sa.Boolean(), nullable=False, server_default="true")
        )

    # Create "General" governance body for each existing organization
    connection = op.get_bind()
    organizations = connection.execute(sa.text("SELECT id FROM organizations")).fetchall()

    for org in organizations:
        org_id = org[0]
        # Insert General governance body
        connection.execute(
            sa.text(
                """
                INSERT INTO governance_bodies
                (organization_id, name, abbreviation, description, color, display_order, is_active, is_default, created_at, updated_at)
                VALUES
                (:org_id, 'General', 'GEN', 'Default governance body for general KPIs', '#3498db', 0, true, true, NOW(), NOW())
            """
            ),
            {"org_id": org_id},
        )

        # Get the governance body ID we just created
        result = connection.execute(
            sa.text("SELECT id FROM governance_bodies WHERE organization_id = :org_id AND is_default = true"),
            {"org_id": org_id},
        ).fetchone()

        if result:
            governance_body_id = result[0]

            # Link all KPIs from this organization to the General governance body
            connection.execute(
                sa.text(
                    """
                    INSERT INTO kpi_governance_body_links (kpi_id, governance_body_id, created_at)
                    SELECT k.id, :gb_id, NOW()
                    FROM kpis k
                    JOIN initiative_system_links isl ON k.initiative_system_link_id = isl.id
                    JOIN initiatives i ON isl.initiative_id = i.id
                    WHERE i.organization_id = :org_id
                """
                ),
                {"gb_id": governance_body_id, "org_id": org_id},
            )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_organization_memberships", schema=None) as batch_op:
        batch_op.drop_column("can_manage_governance_bodies")

    op.drop_table("kpi_governance_body_links")
    op.drop_table("governance_bodies")
    # ### end Alembic commands ###
