"""remove default_organization_id from users

Revision ID: 86d06c10d056
Revises: ea56856d9837
Create Date: 2026-03-20 19:30:10.663841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86d06c10d056'
down_revision = 'ea56856d9837'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_default_organization_id_fkey'), type_='foreignkey')
        batch_op.drop_column('default_organization_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_organization_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('users_default_organization_id_fkey'), 'organizations', ['default_organization_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
