"""add strategy_enabled to organization

Revision ID: 8897660d9e82
Revises: 9a119f8ee479
Create Date: 2026-03-30 06:51:41.312324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8897660d9e82'
down_revision = '9a119f8ee479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strategy_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false'), comment='Enable strategic pillars feature for this organization'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('strategy_enabled')

    # ### end Alembic commands ###
