"""add linked_organization_id to system

Revision ID: 892517c665fb
Revises: 8897660d9e82
Create Date: 2026-03-30 07:57:43.850952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '892517c665fb'
down_revision = '8897660d9e82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('systems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linked_organization_id', sa.Integer(), nullable=True, comment='If set, this system is a portal to another CISK workspace'))
        batch_op.create_foreign_key(None, 'organizations', ['linked_organization_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('systems', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('linked_organization_id')

    # ### end Alembic commands ###
