"""add impact_reinforce_weights to organization

Revision ID: 91554d2e4ea0
Revises: 892517c665fb
Create Date: 2026-03-30 12:21:50.786063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91554d2e4ea0'
down_revision = '892517c665fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('impact_reinforce_weights', sa.JSON(), nullable=True, comment="Exponential reinforcement: {'1': 1, '2': 2, '3': 4}"))
        batch_op.alter_column('impact_calc_method',
               existing_type=sa.VARCHAR(length=30),
               comment='Impact compounding method: simple_product, geometric_mean, toyota_qfd, toyota_weighted_ds, toyota_weighted_full',
               existing_comment='Impact compounding method: simple_product, geometric_mean, toyota_qfd',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.alter_column('impact_calc_method',
               existing_type=sa.VARCHAR(length=30),
               comment='Impact compounding method: simple_product, geometric_mean, toyota_qfd',
               existing_comment='Impact compounding method: simple_product, geometric_mean, toyota_qfd, toyota_weighted_ds, toyota_weighted_full',
               existing_nullable=True)
        batch_op.drop_column('impact_reinforce_weights')

    # ### end Alembic commands ###
