"""add decision_tags to organizations

Revision ID: 9a119f8ee479
Revises: 60b1a5ccaf4c
Create Date: 2026-03-29 19:06:33.960847

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9a119f8ee479'
down_revision = '60b1a5ccaf4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('initiative_progress_updates', schema=None) as batch_op:
        batch_op.alter_column('decisions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Structured decisions: [{what, who, tag}, ...]',
               existing_comment='Structured decisions: [{what, who, tag, mentions}, ...]',
               existing_nullable=True)

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decision_tags', sa.JSON(), nullable=True, comment="Decision tag categories: ['scope', 'budget', ...]"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('decision_tags')

    with op.batch_alter_table('initiative_progress_updates', schema=None) as batch_op:
        batch_op.alter_column('decisions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Structured decisions: [{what, who, tag, mentions}, ...]',
               existing_comment='Structured decisions: [{what, who, tag}, ...]',
               existing_nullable=True)

    # ### end Alembic commands ###
