"""add strategic_pillars table

Revision ID: a79e05c402c8
Revises: 41612386c9e6
Create Date: 2026-03-28 08:27:57.963709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a79e05c402c8'
down_revision = '41612386c9e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategic_pillars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True, comment='Bullet points (one per line)'),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('accent_color', sa.String(length=7), nullable=False),
    sa.Column('icon_data', sa.LargeBinary(), nullable=True, comment='Uploaded icon/image binary'),
    sa.Column('icon_mime_type', sa.String(length=50), nullable=True),
    sa.Column('bs_icon', sa.String(length=50), nullable=True, comment='Bootstrap icon class e.g. bi-rocket-takeoff'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strategic_pillars')
    # ### end Alembic commands ###
