"""Add can_manage_spaces permission

Revision ID: b8447fd59186
Revises: 119d8257cb6a
Create Date: 2026-03-08 19:17:00.814378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8447fd59186'
down_revision = '119d8257cb6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_organization_memberships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_manage_spaces', sa.Boolean(), nullable=False, server_default='true'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_organization_memberships', schema=None) as batch_op:
        batch_op.drop_column('can_manage_spaces')

    # ### end Alembic commands ###
