"""add impact_qfd_matrix to organizations

Revision ID: bca33dac9ddd
Revises: f607688b62d6
Create Date: 2026-03-28 16:54:12.192923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bca33dac9ddd'
down_revision = 'f607688b62d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('impact_qfd_matrix', sa.JSON(), nullable=True, comment="Custom QFD lookup: {'3_3': 3, '3_2': 3, '3_1': 2, ...}"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('impact_qfd_matrix')

    # ### end Alembic commands ###
