"""Add is_org_admin flag to user organization memberships

Revision ID: be485d1bc44f
Revises: 0d21cf9d82e7
Create Date: 2026-03-13 07:57:27.958290

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "be485d1bc44f"
down_revision = "0d21cf9d82e7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("kpi_value_type_configs", schema=None) as batch_op:
        batch_op.alter_column(
            "calculation_config",
            existing_type=postgresql.JSON(astext_type=sa.Text()),
            comment="Configuration for formula calculations: {operation: sum, kpi_config_ids: [1, 2, 3]}",
            existing_comment='Configuration for formula calculations: {operation: "sum", kpi_config_ids: [1, 2, 3]}',
            existing_nullable=True,
        )

    with op.batch_alter_table("system_announcements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_system_announcements_end_date"))
        batch_op.drop_index(batch_op.f("ix_system_announcements_start_date"))

    with op.batch_alter_table("user_organization_memberships", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_org_admin",
                sa.Boolean(),
                nullable=False,
                server_default="false",
                comment="Organization administrator with full permissions",
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_organization_memberships", schema=None) as batch_op:
        batch_op.drop_column("is_org_admin")

    with op.batch_alter_table("system_announcements", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_system_announcements_start_date"), ["start_date"], unique=False)
        batch_op.create_index(batch_op.f("ix_system_announcements_end_date"), ["end_date"], unique=False)

    with op.batch_alter_table("kpi_value_type_configs", schema=None) as batch_op:
        batch_op.alter_column(
            "calculation_config",
            existing_type=postgresql.JSON(astext_type=sa.Text()),
            comment='Configuration for formula calculations: {operation: "sum", kpi_config_ids: [1, 2, 3]}',
            existing_comment="Configuration for formula calculations: {operation: sum, kpi_config_ids: [1, 2, 3]}",
            existing_nullable=True,
        )

    # ### end Alembic commands ###
