"""Add linked KPI value support for cross-org monitoring

Revision ID: bf989a055241
Revises: 07901b5ce63b
Create Date: 2026-03-11 13:12:18.260881

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bf989a055241"
down_revision = "07901b5ce63b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_logs_organization_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_user_id"))

    with op.batch_alter_table("kpi_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_kpi_snapshots_batch_id"))
        batch_op.drop_index(batch_op.f("ix_kpi_snapshots_owner"))
        batch_op.drop_index(batch_op.f("ix_kpi_snapshots_public"))
        batch_op.create_index(batch_op.f("ix_kpi_snapshots_is_public"), ["is_public"], unique=False)
        batch_op.create_index(batch_op.f("ix_kpi_snapshots_owner_user_id"), ["owner_user_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_kpi_snapshots_snapshot_batch_id"), ["snapshot_batch_id"], unique=False)

    with op.batch_alter_table("kpi_value_type_configs", schema=None) as batch_op:
        batch_op.alter_column(
            "target_direction",
            existing_type=sa.VARCHAR(length=20),
            comment="Target direction: maximize (higher is better), minimize (lower is better), or exact (at target)",
            existing_nullable=True,
            existing_server_default=sa.text("'maximize'::character varying"),
        )
        batch_op.alter_column(
            "target_tolerance_pct",
            existing_type=sa.INTEGER(),
            comment="Tolerance percentage for 'exact' target direction",
            existing_nullable=True,
            existing_server_default=sa.text("10"),
        )
        batch_op.alter_column(
            "display_scale",
            existing_type=sa.VARCHAR(length=20),
            comment="Display scale: default, thousands, millions",
            existing_nullable=True,
            existing_server_default=sa.text("'default'::character varying"),
        )
        batch_op.alter_column(
            "display_decimals",
            existing_type=sa.INTEGER(),
            comment="Number of decimals when using display scale (overrides value_type decimals)",
            existing_nullable=True,
        )

    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_organizations_deleted_by"), type_="foreignkey")
        batch_op.create_foreign_key(None, "users", ["deleted_by"], ["id"])

    with op.batch_alter_table("rollup_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rollup_snapshots_batch_id"))
        batch_op.drop_index(batch_op.f("ix_rollup_snapshots_owner"))
        batch_op.drop_index(batch_op.f("ix_rollup_snapshots_public"))
        batch_op.create_index(batch_op.f("ix_rollup_snapshots_is_public"), ["is_public"], unique=False)
        batch_op.create_index(batch_op.f("ix_rollup_snapshots_owner_user_id"), ["owner_user_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_rollup_snapshots_snapshot_batch_id"), ["snapshot_batch_id"], unique=False)

    with op.batch_alter_table("spaces", schema=None) as batch_op:
        batch_op.alter_column(
            "is_private",
            existing_type=sa.BOOLEAN(),
            comment="Private spaces are only visible to users with appropriate permissions",
            existing_nullable=False,
            existing_server_default=sa.text("false"),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("spaces", schema=None) as batch_op:
        batch_op.alter_column(
            "is_private",
            existing_type=sa.BOOLEAN(),
            comment=None,
            existing_comment="Private spaces are only visible to users with appropriate permissions",
            existing_nullable=False,
            existing_server_default=sa.text("false"),
        )

    with op.batch_alter_table("rollup_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rollup_snapshots_snapshot_batch_id"))
        batch_op.drop_index(batch_op.f("ix_rollup_snapshots_owner_user_id"))
        batch_op.drop_index(batch_op.f("ix_rollup_snapshots_is_public"))
        batch_op.create_index(batch_op.f("ix_rollup_snapshots_public"), ["is_public"], unique=False)
        batch_op.create_index(batch_op.f("ix_rollup_snapshots_owner"), ["owner_user_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_rollup_snapshots_batch_id"), ["snapshot_batch_id"], unique=False)

    with op.batch_alter_table("organizations", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_organizations_deleted_by"), "users", ["deleted_by"], ["id"], ondelete="SET NULL"
        )

    with op.batch_alter_table("kpi_value_type_configs", schema=None) as batch_op:
        batch_op.alter_column(
            "display_decimals",
            existing_type=sa.INTEGER(),
            comment=None,
            existing_comment="Number of decimals when using display scale (overrides value_type decimals)",
            existing_nullable=True,
        )
        batch_op.alter_column(
            "display_scale",
            existing_type=sa.VARCHAR(length=20),
            comment=None,
            existing_comment="Display scale: default, thousands, millions",
            existing_nullable=True,
            existing_server_default=sa.text("'default'::character varying"),
        )
        batch_op.alter_column(
            "target_tolerance_pct",
            existing_type=sa.INTEGER(),
            comment=None,
            existing_comment="Tolerance percentage for 'exact' target direction",
            existing_nullable=True,
            existing_server_default=sa.text("10"),
        )
        batch_op.alter_column(
            "target_direction",
            existing_type=sa.VARCHAR(length=20),
            comment=None,
            existing_comment="Target direction: maximize (higher is better), minimize (lower is better), or exact (at target)",
            existing_nullable=True,
            existing_server_default=sa.text("'maximize'::character varying"),
        )

    with op.batch_alter_table("kpi_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_kpi_snapshots_snapshot_batch_id"))
        batch_op.drop_index(batch_op.f("ix_kpi_snapshots_owner_user_id"))
        batch_op.drop_index(batch_op.f("ix_kpi_snapshots_is_public"))
        batch_op.create_index(batch_op.f("ix_kpi_snapshots_public"), ["is_public"], unique=False)
        batch_op.create_index(batch_op.f("ix_kpi_snapshots_owner"), ["owner_user_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_kpi_snapshots_batch_id"), ["snapshot_batch_id"], unique=False)

    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_logs_user_id"), ["user_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_logs_organization_id"), ["organization_id"], unique=False)

    # ### end Alembic commands ###
