"""Add SWOT fields to Space model

Revision ID: e25c8ab9a347
Revises: 9dd04a9578c9
Create Date: 2026-03-11 16:47:36.004474

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e25c8ab9a347"
down_revision = "9dd04a9578c9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("initiatives", schema=None) as batch_op:
        batch_op.alter_column(
            "mission", existing_type=sa.TEXT(), comment="Mission/objectives of the initiative", existing_nullable=True
        )
        batch_op.alter_column(
            "success_criteria", existing_type=sa.TEXT(), comment="Success criteria and metrics", existing_nullable=True
        )
        batch_op.alter_column(
            "responsible_person",
            existing_type=sa.VARCHAR(length=200),
            comment="Person responsible for the initiative",
            existing_nullable=True,
        )
        batch_op.alter_column(
            "team_members",
            existing_type=sa.TEXT(),
            comment="Team members involved (one per line)",
            existing_nullable=True,
        )
        batch_op.alter_column(
            "handover_organization",
            existing_type=sa.VARCHAR(length=200),
            comment="Handover organization/department",
            existing_nullable=True,
        )
        batch_op.alter_column(
            "deliverables",
            existing_type=sa.TEXT(),
            comment="Deliverables and milestones (JSON format)",
            existing_nullable=True,
        )
        batch_op.alter_column(
            "group_label",
            existing_type=sa.VARCHAR(length=1),
            comment="Group label for filtering (A, B, C, or D)",
            existing_nullable=True,
        )

    with op.batch_alter_table("spaces", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("swot_strengths", sa.Text(), nullable=True, comment="SWOT: Internal positive attributes")
        )
        batch_op.add_column(
            sa.Column("swot_weaknesses", sa.Text(), nullable=True, comment="SWOT: Internal negative attributes")
        )
        batch_op.add_column(
            sa.Column("swot_opportunities", sa.Text(), nullable=True, comment="SWOT: External positive factors")
        )
        batch_op.add_column(
            sa.Column("swot_threats", sa.Text(), nullable=True, comment="SWOT: External negative factors")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("spaces", schema=None) as batch_op:
        batch_op.drop_column("swot_threats")
        batch_op.drop_column("swot_opportunities")
        batch_op.drop_column("swot_weaknesses")
        batch_op.drop_column("swot_strengths")

    with op.batch_alter_table("initiatives", schema=None) as batch_op:
        batch_op.alter_column(
            "group_label",
            existing_type=sa.VARCHAR(length=1),
            comment=None,
            existing_comment="Group label for filtering (A, B, C, or D)",
            existing_nullable=True,
        )
        batch_op.alter_column(
            "deliverables",
            existing_type=sa.TEXT(),
            comment=None,
            existing_comment="Deliverables and milestones (JSON format)",
            existing_nullable=True,
        )
        batch_op.alter_column(
            "handover_organization",
            existing_type=sa.VARCHAR(length=200),
            comment=None,
            existing_comment="Handover organization/department",
            existing_nullable=True,
        )
        batch_op.alter_column(
            "team_members",
            existing_type=sa.TEXT(),
            comment=None,
            existing_comment="Team members involved (one per line)",
            existing_nullable=True,
        )
        batch_op.alter_column(
            "responsible_person",
            existing_type=sa.VARCHAR(length=200),
            comment=None,
            existing_comment="Person responsible for the initiative",
            existing_nullable=True,
        )
        batch_op.alter_column(
            "success_criteria",
            existing_type=sa.TEXT(),
            comment=None,
            existing_comment="Success criteria and metrics",
            existing_nullable=True,
        )
        batch_op.alter_column(
            "mission",
            existing_type=sa.TEXT(),
            comment=None,
            existing_comment="Mission/objectives of the initiative",
            existing_nullable=True,
        )

    # ### end Alembic commands ###
