"""add last_organization_id to users

Revision ID: ea56856d9837
Revises: 19d31425d0e7
Create Date: 2026-03-20 19:09:53.763458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea56856d9837'
down_revision = '19d31425d0e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))

    with op.batch_alter_table('kpi_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kpi_snapshots_batch_id'))
        batch_op.drop_index(batch_op.f('ix_kpi_snapshots_owner'))
        batch_op.drop_index(batch_op.f('ix_kpi_snapshots_public'))
        batch_op.create_index(batch_op.f('ix_kpi_snapshots_is_public'), ['is_public'], unique=False)
        batch_op.create_index(batch_op.f('ix_kpi_snapshots_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kpi_snapshots_snapshot_batch_id'), ['snapshot_batch_id'], unique=False)

    with op.batch_alter_table('kpi_value_type_configs', schema=None) as batch_op:
        batch_op.alter_column('display_scale',
               existing_type=sa.VARCHAR(length=20),
               comment='Display scale: default, thousands, millions',
               existing_nullable=True,
               existing_server_default=sa.text("'default'::character varying"))
        batch_op.alter_column('display_decimals',
               existing_type=sa.INTEGER(),
               comment='Number of decimals when using display scale (overrides value_type decimals)',
               existing_nullable=True)
        batch_op.alter_column('linked_source_org_id',
               existing_type=sa.INTEGER(),
               comment='Source organization for linked KPI values (can be same org or different org)',
               existing_nullable=True)
        batch_op.alter_column('linked_source_kpi_id',
               existing_type=sa.INTEGER(),
               comment='Source KPI to read values from (deletion blocked while linked)',
               existing_nullable=True)
        batch_op.alter_column('linked_source_value_type_id',
               existing_type=sa.INTEGER(),
               comment='Source value type to read from (must match type/unit)',
               existing_nullable=True)

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_organizations_deleted_by'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['deleted_by'], ['id'])

    with op.batch_alter_table('rollup_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rollup_snapshots_batch_id'))
        batch_op.drop_index(batch_op.f('ix_rollup_snapshots_owner'))
        batch_op.drop_index(batch_op.f('ix_rollup_snapshots_public'))
        batch_op.create_index(batch_op.f('ix_rollup_snapshots_is_public'), ['is_public'], unique=False)
        batch_op.create_index(batch_op.f('ix_rollup_snapshots_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rollup_snapshots_snapshot_batch_id'), ['snapshot_batch_id'], unique=False)

    with op.batch_alter_table('spaces', schema=None) as batch_op:
        batch_op.alter_column('is_private',
               existing_type=sa.BOOLEAN(),
               comment='Private spaces are only visible to users with appropriate permissions',
               existing_nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_organization_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_users_default_organization'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'organizations', ['last_organization_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_users_default_organization'), 'organizations', ['default_organization_id'], ['id'])
        batch_op.drop_column('last_organization_id')

    with op.batch_alter_table('spaces', schema=None) as batch_op:
        batch_op.alter_column('is_private',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Private spaces are only visible to users with appropriate permissions',
               existing_nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('rollup_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rollup_snapshots_snapshot_batch_id'))
        batch_op.drop_index(batch_op.f('ix_rollup_snapshots_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_rollup_snapshots_is_public'))
        batch_op.create_index(batch_op.f('ix_rollup_snapshots_public'), ['is_public'], unique=False)
        batch_op.create_index(batch_op.f('ix_rollup_snapshots_owner'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rollup_snapshots_batch_id'), ['snapshot_batch_id'], unique=False)

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_organizations_deleted_by'), 'users', ['deleted_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('kpi_value_type_configs', schema=None) as batch_op:
        batch_op.alter_column('linked_source_value_type_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Source value type to read from (must match type/unit)',
               existing_nullable=True)
        batch_op.alter_column('linked_source_kpi_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Source KPI to read values from (deletion blocked while linked)',
               existing_nullable=True)
        batch_op.alter_column('linked_source_org_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Source organization for linked KPI values (can be same org or different org)',
               existing_nullable=True)
        batch_op.alter_column('display_decimals',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of decimals when using display scale (overrides value_type decimals)',
               existing_nullable=True)
        batch_op.alter_column('display_scale',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Display scale: default, thousands, millions',
               existing_nullable=True,
               existing_server_default=sa.text("'default'::character varying"))

    with op.batch_alter_table('kpi_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kpi_snapshots_snapshot_batch_id'))
        batch_op.drop_index(batch_op.f('ix_kpi_snapshots_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_kpi_snapshots_is_public'))
        batch_op.create_index(batch_op.f('ix_kpi_snapshots_public'), ['is_public'], unique=False)
        batch_op.create_index(batch_op.f('ix_kpi_snapshots_owner'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kpi_snapshots_batch_id'), ['snapshot_batch_id'], unique=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###
