"""Add linked source columns to kpi_value_type_configs

Revision ID: f117f9b6cec6
Revises: bf989a055241
Create Date: 2026-03-11 13:19:15.298170

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f117f9b6cec6"
down_revision = "bf989a055241"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("kpi_value_type_configs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "linked_source_org_id",
                sa.Integer(),
                nullable=True,
                comment="Source organization for linked KPI values (can be same org or different org)",
            )
        )
        batch_op.add_column(
            sa.Column(
                "linked_source_kpi_id",
                sa.Integer(),
                nullable=True,
                comment="Source KPI to read values from (deletion blocked while linked)",
            )
        )
        batch_op.add_column(
            sa.Column(
                "linked_source_value_type_id",
                sa.Integer(),
                nullable=True,
                comment="Source value type to read from (must match type/unit)",
            )
        )
        batch_op.create_foreign_key(None, "organizations", ["linked_source_org_id"], ["id"], ondelete="RESTRICT")
        batch_op.create_foreign_key(None, "kpis", ["linked_source_kpi_id"], ["id"], ondelete="RESTRICT")
        batch_op.create_foreign_key(None, "value_types", ["linked_source_value_type_id"], ["id"], ondelete="RESTRICT")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("kpi_value_type_configs", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("linked_source_value_type_id")
        batch_op.drop_column("linked_source_kpi_id")
        batch_op.drop_column("linked_source_org_id")

    # ### end Alembic commands ###
