"""Add comment permissions

Revision ID: f3a9b2c1d5e7
Revises: e6f86e8171ac
Create Date: 2026-03-09 23:00:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f3a9b2c1d5e7"
down_revision = "e6f86e8171ac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_organization_memberships", schema=None) as batch_op:
        batch_op.add_column(sa.Column("can_view_comments", sa.Boolean(), nullable=False, server_default="true"))
        batch_op.add_column(sa.Column("can_add_comments", sa.Boolean(), nullable=False, server_default="true"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_organization_memberships", schema=None) as batch_op:
        batch_op.drop_column("can_add_comments")
        batch_op.drop_column("can_view_comments")

    # ### end Alembic commands ###
