"""add impact_calc_method to organizations

Revision ID: f607688b62d6
Revises: 1f7bd9f9e317
Create Date: 2026-03-28 16:47:28.994659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f607688b62d6'
down_revision = '1f7bd9f9e317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('impact_calc_method', sa.String(length=30), nullable=True, comment='Impact compounding method: simple_product, geometric_mean, toyota_qfd'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('impact_calc_method')

    # ### end Alembic commands ###
